node = '测试'


[user_conf]
    [user_conf.check]
    # check config

    [user_conf.handler]
    # handler config
    table_name = 'test_table'
    field_name_list = ['Msg']
    unit = 's'


[sender]
    lua_path = 'lua\enque_script.lua'
    enque_log = true


[redis]
    db= 1
    host= 'localhost'
    port= 6379


[web]
    set_name = 'status'
    order_status = 'get_status'


[log_configuration]
    console = true
    console_level = 'DEBUG'   #'DEBUG','INFO','WARNING','ERROR','CRITICAL'
    file = true
    file_level = 'DEBUG'  #'DEBUG','INFO','WARNING','ERROR','CRITICAL'
    log_file = 'logs/log.log'
    backup_count = 5
    max_size = 10240
    format_string = '(%(asctime)s), %(levelname)s, <%(threadName)s>, %(module)s, %(funcName)s, [%(lineno)d]: %(message)s'

